version: '3.8'

services:
  nginx:
    # https://github.com/czerasz/docker-nginx-geoip2/blob/master/Dockerfile
    image: czerasz/nginx-geoip2:latest
    container_name: nginx-load-balancer
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "8091:80"